// src/App.tsx
import type { Component, JSXElement } from "solid-js";
import type {} from "solid-styled-jsx";

function One(): JSXElement {
    return (
        <>
            <div class="main">MJ Adendorff</div>
            <style jsx dynamic>{`
                .main {
                    background-color: black;
                    color: green;
                    height: 100vh;
                    width: 100%;
                    display: flex;
                    justify-content: center;
                    align-items: center;
                }
            `}</style>
        </>
    );
}

const App: Component = () => {
    return <One />;
};

export default App;

// src/App.svelte
<script>
  import Router from 'svelte-spa-router';
  import routes from "./routes";
</script>

<main>
  <div class="container">
    <Router {routes} />
  </div>
</main>

<style>
  .container {
    background-color: black;
    display: flex;
    flex-direction: column;
    height: 100vh;
    width: 100%;
    color: white;
    font-family: "vt323";
    justify-content: center;
    align-items: center;
    border: 10px solid grey;
  }
</style>
