// src/pages/Home.svelte
<script>
	import Button from "../lib/Button.svelte";
</script>

<main>
	<div class="heading">
		<div>
			<h1>MJ Adendorff</h1>
			<h3>Software Developer</h3>
		</div>
	</div>
	<div class="buttons">
		<Button text="About Me" />
		<Button text="Education" to="/education" done />
		<Button text="Experience" />
		<Button text="Portfolio" />
		<Button text="Github" to="https://github.com/" done/>
	</div>
</main>

<style lang="less">
	.heading {
		display: flex;
		flex-direction: column;
		align-items: center;
	}
	h3 {
		color: lightblue;
		&::before {
			content: ">>\0020";
		}
		&:hover::before {
			content: "<<\0020";
		}
	}
	.buttons {
		display: flex;
		gap: 10px;
		flex-wrap: wrap;
		padding: 30px;
		justify-content: center;
		align-items: center;
		max-width: 500px;
	}
</style>

// src/Home.tsx
import type { Component } from "solid-js";
import { AiOutlineCode } from "solid-icons/ai";
// Page 1
const One: Component = () => {
    const main: any = {
        "background-color": "#091069",
        display: "flex",
        "justify-content": "center",
        "align-items": "center",
        height: "100vh",
        width: "100%",
    };
    const container: any = {
        display: "flex",
        "justify-content": "center",
        "align-items": "center",
        "flex-direction": "column",
        gap: "20px",
    };
    const name: any = {
        color: "white",
        "font-size": "60px",
        "font-weight": "900",
        "text-transform": "uppercase",
    };
    const logo: any = {
        "background-color": "#BDCCDA",
        "border-radius": "50%",
        color: "white",
        "font-size": "80px",
        padding: "25px",
        display: "flex",
        "justify-content": "center",
        "align-items": "center",
        margin: "0",
    };
    const subName: any = {
        color: "#BDCCDA",
    };
    return (
        <>
            <div style={main}>
                <div style={container}>
                    <div style={logo}>
                        <AiOutlineCode color={"#091069"} />
                    </div>
                    <div style={name}>MJ Adendorff</div>
                    <div style={subName}>Fullstack Developer</div>
                </div>
            </div>
        </>
    );
};

// Page 2
const Two: Component = () => {
    const style: any = {
        "background-color": "#2B4D9D",
        display: "flex",
        "justify-content": "center",
        "align-items": "center",
        height: "100vh",
        width: "100%",
        color: "green",
    };
    return (
        <>
            <div style={style}>Education</div>
        </>
    );
};

// Page 2
const Three: Component = () => {
    const style: any = {
        "background-color": "#95ABD0",
        display: "flex",
        "justify-content": "center",
        "align-items": "center",
        height: "100vh",
        width: "100%",
        color: "green",
    };
    return (
        <>
            <div style={style}>Hello</div>
        </>
    );
};
// The Page Layout
const Home: Component = () => {
    return (
        <div>
            <One />
            <Two />
            <Three />
        </div>
    );
};

export default Home;
